name: release

on:
  workflow_dispatch:

  push:
    branches:
      - workflow-test

jobs:
  build_desktop:
    name: Build desktop app for ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      TAURI_SIGNING_PRIVATE_KEY: "${{ secrets.TAURI_PRIVATE_KEY }}"
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: "${{ secrets.TAURI_KEY_PASSWORD }}"
      APPLE_CERTIFICATE: "${{ secrets.APPLE_CERTIFICATE }}"
      APPLE_CERTIFICATE_PASSWORD: "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}"
      APPLE_SIGNING_IDENTITY: "${{ secrets.APPLE_SIGNING_IDENTITY }}"
      APPLE_ID: "${{ secrets.APPLE_ID }}"
      APPLE_PASSWORD: "${{ secrets.APPLE_PASSWORD }}"
      APPLE_TEAM_ID: "${{ secrets.APPLE_TEAM_ID }}"

    steps:
      ### system setup

      - uses: actions/checkout@v4

      ### LINUX

      - name: linux > build
        run: make TAURI_SIGNING_PRIVATE_KEY="${{ secrets.TAURI_PRIVATE_KEY }}" TAURI_SIGNING_PRIVATE_KEY_PASSWORD="${{ secrets.TAURI_KEY_PASSWORD }}" build_docker_tauri
        if: matrix.platform == 'ubuntu-latest'

      - name: linux > upload artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux_artifacts
          if-no-files-found: error
          path: |
            src-tauri/target/release/bundle/deb/elasticvue_*_amd64.deb
            src-tauri/target/release/bundle/appimage/elasticvue_*_amd64.*
            src-tauri/target/release/elasticvue


  build_browser_extensions:
    name: Build browser extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build extensions
        run: make build_browser_extensions

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: browser_extension_artifacts
          if-no-files-found: error
          path: |
            artifacts/*.zip

